name: CI/CD Pipeline

on:
  push:
    branches: [ main, new-branch ]
  pull_request:
    branches: [ main, new-branch ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 bandit
      - name: Lint code
        run: flake8 .
      - name: Vulnerability scan
        run: bandit -r .

  test:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest tests/ -v

  docker-build-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Debug Docker secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME missing"; else echo "DOCKER_USERNAME exists"; fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "DOCKER_PASSWORD missing"; else echo "DOCKER_PASSWORD exists"; fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t robinyaghi/multicontainer2:latest .

      - name: Test Docker container
        run: |
          docker run --rm \
            -e REDIS_HOST=redis \
            -e REDIS_PORT=6379 \
            robinyaghi/multicontainer2:latest python -m pytest tests/ -v
